@startuml

object Main
object gamePlay
object player
object dice
object board
object field
object chanceCard
object bank
object chance
object busniess
object plot
object tax
object prison
object visit
object Deck
object parking
object proptertyField
object Deed
object ferries
object soda

Main *-- gamePlay
gamePlay o-- "2..6" player: has
field <|-- proptertyField
prison *-- "1" visit
gamePlay *-- "2" dice: has
field *--"6" busniess: has
ferries *--"2" busniess: has
soda *--"4" busniess: has
board *-- field
proptertyField <|-- "1" prison: has
proptertyField <|-- "2" tax: has
proptertyField <|-- "1" parking: has
proptertyField <|-- "28" plot: has
proptertyField <|-- "6" chance: has
gamePlay o-- "1" bank: has
gamePlay *-- "1" board: has
gamePlay *-- "1" Deck: has
Deck *-- "46" chanceCard: has
player *-- Deed

@enduml