@startuml
'https://plantuml.com/sequence-diagram

Main -> Game: new()
Main -> Game: setup()
Game -> TextUI: new()
Game -> FileIO: new()
Game -> FileIO: readData()
FileIO --> Game: ArrayList<String>
alt data[] not empty && continue saved game
loop for each s in data[]
Game -> Player: new()
end

else
Game -> Game: registerPlayer()
end

@enduml