@startuml
'https://plantuml.com/sequence-diagram

participant Game as game
participant TextUI as ui
participant SubField  as subField
participant Field  as field

game -> ui : response = promptText( msg )

ui --> game : "Y"
game -> field : msg = processResponse(player, response )

alt response "Y"
    field  -> subField : onAccept(player)
    subField  -> Player: buyProperty(this)
    Player -> Account : withdraw(costOfField)
    subField --> game : "Egon købte Valbylanggade"
else response "N"
    field -> subField : onReject(player)
    end


game -> ui : displayMessage( msg )

@enduml