@startuml
'https://plantuml.com/sequence-diagram

Main -> Game: new()
'indsæt de kald der mangler herfra og ned til at vi tjekker om der var noget spildata
alt data[] not empty && continue saved game
loop data[]
Game -> Player: new(name, balance)
end
else
Game -> Game: registerPlayers()

end
'indsæt de to sidste kald

@enduml

